### ISSUE TITLE
Crew photos

### ISSUE THREAD

**Issue by marinov-tomislav** [NikolayBa/AUBGOlympics#13]
They are finally here!

https://drive.google.com/drive/folders/0B5k0YNr5-Tqtc29tOVFDY212NUE

The new crew photos should be uploaded to our website. Would be best if it could happen by tonight, as we will be releasing them in the evening most probably. If not, we'll survive.

There are two photos per person - one blank and one filled in.

The blank photos should be displayed when the page loads. When the user does a mouse over on one of the photos, it should temporarily change to the filled in photo. Text with the name and department of the person should also pop up like it does now.

It would be nice if the crew can be separated by departments, as the wings are unique per department as well.

Martin, Mina, Tommy and Tisho should be at the top of the page with their titles listed.

Martin and Tommy will help with JavaScript for the web page in the evening. What needs to be done ASAP is to organize the layout of the page and inserting just the blank photos. We'll load the rest dynamically with JavaScript.

Rename the photos to a simple name. 
Example: martin-blank.png and martin-fill.png. They should all have consistent names.

**Comment by nikolastanimirov** [comment]
https://drive.google.com/open?id=0B71eAqBLiA7TenBnRm12cjJZQlU 
compatible photo names with the new page
